import { SENSOR_FRAME_BYTES, SENSOR_FRAME_BYTES_V1 } from './constants.js';

/**
 * Recorded sensor streams (ARCHITECTURE.md 8).
 *
 * A swing cannot be performed twice the same way, so tuning a detector against
 * a live phone means arguing with a memory. A trace is the same motion every
 * time, which turns "it feels like it misses some" into a number that a test
 * can hold on to.
 *
 * The format is deliberately dull: one JSON header line, then one frame per
 * line as hex. Hex rather than base64 because it needs no platform helpers and
 * works identically in Node and the browser; these are development artefacts,
 * not something to optimise.
 */

export const TRACE_VERSION = 1;
export const TRACE_EXTENSION = '.pmtrace';

export interface TraceHeader {
  readonly trace: typeof TRACE_VERSION;
  readonly roomCode: string;
  readonly playerId: number;
  /** ISO timestamp of when recording began, for the human reading the file. */
  readonly startedAt: string;
  /** What was being done while this was recorded. */
  readonly note: string;
  /** Set for traces generated by a script rather than captured from a phone. */
  readonly synthetic?: boolean;
}

const HEX = '0123456789abcdef';

export function bytesToHex(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let out = '';
  for (const byte of bytes) {
    out += HEX[byte >> 4];
    out += HEX[byte & 15];
  }
  return out;
}

export class MalformedTraceError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'MalformedTraceError';
  }
}

export function hexToBytes(hex: string): ArrayBuffer {
  const trimmed = hex.trim();
  if (trimmed.length % 2 !== 0) {
    throw new MalformedTraceError(`Hex frame has an odd length: ${trimmed.length}`);
  }
  const bytes = new Uint8Array(trimmed.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    const byte = Number.parseInt(trimmed.slice(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(byte)) throw new MalformedTraceError('Hex frame contains a non-hex digit');
    bytes[i] = byte;
  }
  return bytes.buffer;
}

export function encodeTraceHeader(header: TraceHeader): string {
  return JSON.stringify(header);
}

export function parseTraceHeader(line: string): TraceHeader {
  let parsed: unknown;
  try {
    parsed = JSON.parse(line);
  } catch {
    throw new MalformedTraceError('First line of a trace must be its JSON header');
  }
  if (typeof parsed !== 'object' || parsed === null || !('trace' in parsed)) {
    throw new MalformedTraceError('Trace header is missing the "trace" version field');
  }
  return parsed as TraceHeader;
}

export interface ParsedTrace {
  readonly header: TraceHeader;
  /** Frames in the order they arrived, still encoded. */
  readonly frames: readonly ArrayBuffer[];
}

export function parseTrace(text: string): ParsedTrace {
  const lines = text.split('\n').filter((line) => line.trim().length > 0);
  const [headerLine, ...frameLines] = lines;
  if (headerLine === undefined) throw new MalformedTraceError('Trace file is empty');

  const header = parseTraceHeader(headerLine);
  const frames = frameLines.map((line, index) => {
    const buffer = hexToBytes(line);
    if (buffer.byteLength !== SENSOR_FRAME_BYTES && buffer.byteLength !== SENSOR_FRAME_BYTES_V1) {
      throw new MalformedTraceError(
        `Frame ${index + 1} is ${buffer.byteLength} bytes, expected ` +
          `${SENSOR_FRAME_BYTES} or ${SENSOR_FRAME_BYTES_V1}`,
      );
    }
    return buffer;
  });

  return { header, frames };
}

export function serializeTrace(header: TraceHeader, frames: readonly ArrayBuffer[]): string {
  return [encodeTraceHeader(header), ...frames.map(bytesToHex)].join('\n') + '\n';
}
